// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportHTML(arg1) {
  return window['go']['main']['App']['ExportHTML'](arg1);
}

export function GetRecentDocuments() {
  return window['go']['main']['App']['GetRecentDocuments']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function NewDocument() {
  return window['go']['main']['App']['NewDocument']();
}

export function OpenDocument() {
  return window['go']['main']['App']['OpenDocument']();
}

export function ReadDocument(arg1) {
  return window['go']['main']['App']['ReadDocument'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveDocument(arg1, arg2) {
  return window['go']['main']['App']['SaveDocument'](arg1, arg2);
}

export function SaveDocumentAs(arg1) {
  return window['go']['main']['App']['SaveDocumentAs'](arg1);
}

export function UpdateRecentDocument(arg1) {
  return window['go']['main']['App']['UpdateRecentDocument'](arg1);
}
