// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DebugLog(arg1:string):Promise<void>;

export function ExportHTML(arg1:models.ExportPayload):Promise<models.SaveResult>;

export function GetRecentDocuments():Promise<Array<models.RecentDocument>>;

export function LoadConfig():Promise<models.AppConfig>;

export function LoadHotkeys():Promise<Array<models.HotkeyBinding>>;

export function NewDocument():Promise<models.DocumentMeta>;

export function OpenDocument():Promise<models.DocumentPayload>;

export function OpenFolder():Promise<models.Workspace>;

export function PickMdFile():Promise<string>;

export function ReadDocument(arg1:string):Promise<models.DocumentPayload>;

export function ResetHotkeys():Promise<Array<models.HotkeyBinding>>;

export function SaveConfig(arg1:models.AppConfig):Promise<models.AppConfig>;

export function SaveDocument(arg1:string,arg2:string):Promise<models.SaveResult>;

export function SaveDocumentAs(arg1:string):Promise<models.SaveResult>;

export function SaveHotkeys(arg1:Array<models.HotkeyBinding>):Promise<Array<models.HotkeyBinding>>;

export function ScanFolder(arg1:string):Promise<models.Workspace>;

export function UpdateRecentDocument(arg1:string):Promise<void>;
